# Generated by Django 4.2.4 on 2023-08-17 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('critratmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='titles',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
