# Generated by Django 4.2.4 on 2023-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critratmain', '0002_main_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritRats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critrats', models.CharField(max_length=50)),
            ],
        ),
    ]
